language: cpp

compiler:
  - gcc

env:
  - CXXSTD=''
  - CXXSTD='cxxflags="-std=c++0x"'

before_install:
 - wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2/download -O /tmp/boost.tar.bz2
 - tar jxf /tmp/boost.tar.bz2
 - mv boost_1_57_0 $PWD/boost-trunk
 - export BOOST_ROOT="$PWD/boost-trunk"
 - cd $BOOST_ROOT
 - ./bootstrap.sh
 - cd $TRAVIS_BUILD_DIR

script:
 - $BOOST_ROOT/b2 toolset=$CC$GCCVER $CXXSTD
